### PR TITLE
Added RemoveCommand() function

### PR DESCRIPTION
**Pull request by abluescarab**
I have a project that adds and removes commands on the fly based on user input, but there was no RemoveCommand() that I could find. I needed to make sure that the command could be removed in case the user accidentally overwrote an in-game function. (There are safeguards, but I don't think there's a way to get a list of everything in-game that shouldn't be overwritten...)

**Edit:** For anyone who sees this commit, the better way is to use an event listener and check user input against a list of accepted values.

### CODE REVIEW

**Comment by Arkhist** [comment]
I'm not agreeing of this method use for active modding (using this as a feature).

But this could be nice for unloading mods.

**Comment by Spartan322** [comment]
I'm not pulling this because it goes against what the command system is designed for, if you need the functionality of this idea, just use the event system and listen to CommandSentEvent, but this is not gonna be standard functionality simply because there is no reason for it to be.

**Comment by Arkhist** [comment]
Even for unloading mods ? That could be a nice addition. But private method.

**Comment by Spartan322** [comment]
unloading will be auto handled, the reason the unload method exists in the mod interface is for things beyond the actual mod system that the player added themselves.

**Pull request closed without merging**
