### PR TITLE
Add ConvertToXElement method to ElementInfo

### PR DESCRIPTION
**Pull request by tenesiss**
Add `ConvertToXElement` method to ElementInfo

Related to issue #177

### CODE REVIEW

**Comment by SoundOfScooting** [comment]
I don't see the need for two versions of this method to exist (I would remove the static method).
Also, if there are to be two, one of them should probably call the other instead of having all of the code repeated.

**Comment by tenesiss** [comment]
> I don't see the need for two versions of this method to exist (I would remove the static method). However, if there are to be two, one of them should probably call the other instead of having all of the code repeated.

I think the static one can be useful in some specific cases, however I probably will call the static one in the other giving `this` as parameter

**Comment by SoundOfScooting** [comment]
Line 78 is blank.

**Comment by Spartan322** [comment]
I don't see what the point of the static method would serve, in any case you have an ElementInfo you can just call the Convert method on it, it actually would cause an NRE in the method if the ElementInfo was null.

**Pull request merged**
